import "@/app/globals.css";

import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { hasLocale, NextIntlClientProvider } from "next-intl";

import Layout from "@/app/_module/layout";
import { fonts } from "@/app/fonts";
import { Providers } from "@/app/providers";
import { routing } from "@/i18n/routing";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: Promise<{ locale: string }>
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html
      lang={locale}
      className={fonts.map((f) => f.variable).join(" ")}
      data-scroll-behavior="smooth"
    >
      <body className="tw:font-pretendard tw:antialiased">
        <NextIntlClientProvider>
          <Providers>
            <Layout>
              {children}
            </Layout>
          </Providers>
        </NextIntlClientProvider>
        <div id="portal" />
      </body>
    </html>
  );
}
